#ifndef Py_INTERNAL_PYSPEC_H
#define Py_INTERNAL_PYSPEC_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#include "pycore_tstate.h"         // _PyThreadStateImpl

/* Call tables generated from pyspec files (Objects/pyspec/<file>.py) by
 * Argument Clinic (Tools/clinic/libclinic/pyspec/call_table.py, run by
 * "make clinic"), one per spec'd class, all listed in the registry below.
 * For a builtin type whose __new__ is implemented by a spec, the table
 * lists direct C entry points for calls of the type with
 * positional, object-typed arguments only, and facts about their results
 * derived from the spec code.  The tier-2 optimizer
 * uses them to replace _CALL_BUILTIN_CLASS by a direct call and to type
 * or fold the result.  The table also has the facts of the other methods
 * of the type the spec implements, keyed by their ml_meth, and of its
 * slots with a Python reference, keyed by slot.  Every fact
 * holds only for the exact argument type of its entry (a subclass
 * instance matches the generic entry).  The data is static: no startup
 * cost. */

/* The call may execute arbitrary Python code (__bytes__, __index__,
 * iterators, codecs, ...). */
#define _PySpec_MAY_RUN_PYTHON  (1 << 0)
/* The call always raises: it never returns a result. */
#define _PySpec_ALWAYS_RAISES   (1 << 1)

typedef PyObject *(*_PySpecFunc0)(void);
typedef PyObject *(*_PySpecFunc1)(PyObject *);

typedef struct {
    /* Number of positional arguments, all PyObject *. */
    uint8_t nargs;
    /* _PySpec_* flags. */
    uint8_t flags;
    /* Py_CONSTANT_* the call always returns, without side effects and
       without raising; -1 if none. */
    int8_t result_const;
    /* Index of the argument the call always returns (a new reference to
       that very object), or -1.  E.g. 0 for bytes(b) and b.__bytes__()
       when type(b) is exactly bytes. */
    int8_t result_alias;
    /* The exact type of the first argument this entry is specialized
       for, or NULL for any argument. */
    PyTypeObject *arg_type;
    /* The exact type of every result, or NULL when unknown (e.g. a
       subclass instance may be returned). */
    PyTypeObject *result_type;
    /* Calls of the type: the function to call; returns a new reference,
     * or NULL with an exception set.
     * Methods: the ml_meth of the method, which identifies it. */
    union {
        _PySpecFunc0 f0;
        _PySpecFunc1 f1;
        PyCFunction meth;
    } func;
} _PySpecCall;

/* The key of a slot: the offset of its member in PyHeapTypeObject, as in
 * slotdefs[] of Objects/typeobject.c, e.g.
 * _PySpec_SLOT(as_mapping.mp_subscript), _PySpec_SLOT(ht_type.tp_iternext). */
#define _PySpec_SLOT(MEMBER) ((uint16_t)offsetof(PyHeapTypeObject, MEMBER))

/* The facts of a slot of a spec'd class that has a Python reference (a
 * @c_implemented dunder), for self of exactly that class: the facts of
 * calling the special method, e.g. b[i] for bytes.__getitem__.  In
 * facts, nargs counts self, arg_type is the exact type of the argument
 * after self (NULL: any), and func is not used. */
typedef struct {
    /* _PySpec_SLOT() of the first slot of the dunder in slotdefs[] that
       the class fills: the one its wrapper calls. */
    uint16_t slot;
    /* The special method, "__getitem__": for tests and debugging only. */
    const char *name;
    _PySpecCall facts;
} _PySpecSlot;

typedef struct {
    PyTypeObject *type;
    /* Calls of the type (tp_new): positional arguments only. */
    Py_ssize_t ncalls;
    const _PySpecCall *calls;
    /* Methods and class methods implemented by the spec.  The arguments
       are self and the others for a method, and the others for a class
       method; nargs counts them.  The generic entry of a class method
       holds for any class, the others only for the type itself (see
       _PySpec_FindMethod()). */
    Py_ssize_t nmethods;
    const _PySpecCall *methods;
    /* The slots of the class with a Python reference. */
    Py_ssize_t nslots;
    const _PySpecSlot *slots;
} _PySpecCallTable;

/* The registry: every call table (defined in the Objects/clinic/
 * <file>_pyspec.c.h of its spec, exported for _testinternalcapi), and
 * _PySpec_REGISTRY(X), which is X(table) for each. */
/*[pyspec registry start]*/
/* Generated by Argument Clinic (Tools/clinic/libclinic/pyspec/call_table.py)
 * from the specs of the core C files; do not edit: run clinic on a spec'd
 * C file. */
/* Objects/pyspec/bytesobject.py */
PyAPI_DATA(const _PySpecCallTable) _PySpec_bytes_calls;
PyAPI_DATA(const _PySpecCallTable) _PySpec_bytes_iterator_calls;
#define _PySpec_REGISTRY(X) \
    X(_PySpec_bytes_calls) \
    X(_PySpec_bytes_iterator_calls)
/*[pyspec registry end]*/

/* The call table of type tp, or NULL. */
static inline const _PySpecCallTable *
_PySpec_GetCallTable(PyTypeObject *tp)
{
#define _PySpec_MATCH(TABLE) \
    if ((TABLE).type == tp) { \
        return &(TABLE); \
    }
    _PySpec_REGISTRY(_PySpec_MATCH)
#undef _PySpec_MATCH
    return NULL;
}

/* The table entry for tp(arg, ...) with nargs positional arguments.
 * arg_type is the exact type of the single argument when known, or NULL;
 * an entry specialized for it is preferred over the generic one. */
static inline const _PySpecCall *
_PySpec_FindCall(PyTypeObject *tp, int nargs, PyTypeObject *arg_type)
{
    const _PySpecCallTable *table = _PySpec_GetCallTable(tp);
    if (table == NULL) {
        return NULL;
    }
    const _PySpecCall *generic = NULL;
    for (Py_ssize_t i = 0; i < table->ncalls; i++) {
        const _PySpecCall *call = &table->calls[i];
        if (call->nargs != nargs) {
            continue;
        }
        if (call->arg_type == NULL) {
            generic = call;
        }
        else if (call->arg_type == arg_type) {
            return call;
        }
    }
    return generic;
}

/* The facts of the special method of slot slot_id (_PySpec_SLOT(), a slot
 * with a Python reference in a spec) of self of exact type tp, called
 * with an argument of exact type arg_type after self (NULL when unknown
 * or none); an entry specialized for arg_type is preferred over the
 * generic one.  NULL when the spec has none.  A specialized uop that does
 * what the slot does (the interpreter's own copy of its C) takes its
 * result facts from here, so that they are those derived from the spec;
 * the debug build checks them at run time (_ASSERT_RESULT_TYPE) and
 * test_pyspec_facts checks the entries against the slot. */
static inline const _PySpecCall *
_PySpec_FindSlot(PyTypeObject *tp, uint16_t slot_id, PyTypeObject *arg_type)
{
    const _PySpecCallTable *table = _PySpec_GetCallTable(tp);
    if (table == NULL) {
        return NULL;
    }
    const _PySpecCall *generic = NULL;
    for (Py_ssize_t i = 0; i < table->nslots; i++) {
        const _PySpecSlot *slot = &table->slots[i];
        if (slot->slot != slot_id) {
            continue;
        }
        if (slot->facts.arg_type == NULL) {
            generic = &slot->facts;
        }
        else if (slot->facts.arg_type == arg_type) {
            return &slot->facts;
        }
    }
    return generic;
}

/* "Runs no Python code" tripwire.  In debug builds, a call that the facts
 * say runs no Python code (an entry without _PySpec_MAY_RUN_PYTHON) is made
 * between _PySpec_EnterNoPython() and _PySpec_LeaveNoPython(), and
 * _PyEval_EvalFrameDefault() calls _PySpec_CheckPythonAllowed(): every
 * Python function, method, slot wrapper, generator or finalizer runs
 * through it, so a wrong fact is a fatal error at the call that ran Python.
 * In release builds these do nothing. */
#ifdef Py_DEBUG
static inline int
_PySpec_EnterNoPython(PyThreadState *tstate)
{
    _PyThreadStateImpl *ts = (_PyThreadStateImpl *)tstate;
    int saved = ts->pyspec_no_python;
    ts->pyspec_no_python = 1;
    return saved;
}

static inline void
_PySpec_LeaveNoPython(PyThreadState *tstate, int saved)
{
    ((_PyThreadStateImpl *)tstate)->pyspec_no_python = saved;
}

/* code: the code object about to run. */
static inline void
_PySpec_CheckPythonAllowed(PyThreadState *tstate, PyCodeObject *code)
{
    if (((_PyThreadStateImpl *)tstate)->pyspec_no_python) {
        const char *name = PyUnicode_AsUTF8(code->co_qualname);
        const char *file = PyUnicode_AsUTF8(code->co_filename);
        _Py_FatalErrorFormat(
            __func__,
            "%s (%s:%d) runs inside a call that the pyspec facts say runs "
            "no Python code: a derived fact is wrong (see "
            "Include/internal/pycore_pyspec.h)",
            name ? name : "?", file ? file : "?", code->co_firstlineno);
    }
}
#else
#  define _PySpec_EnterNoPython(tstate) ((void)(tstate), 0)
#  define _PySpec_LeaveNoPython(tstate, saved) ((void)(tstate), (void)(saved))
#  define _PySpec_CheckPythonAllowed(tstate, code) ((void)(tstate), (void)(code))
#endif

/* Call func, from an entry without _PySpec_MAY_RUN_PYTHON: it runs no
 * Python code (checked in debug builds).  This does not mean that the call
 * does not escape: e.g. a critical section may detach the thread, and
 * releasing a buffer may decref another object. */
static inline PyObject *
_PySpec_CallNoPython1(PyThreadState *tstate, _PySpecFunc1 func, PyObject *arg)
{
    int saved = _PySpec_EnterNoPython(tstate);
    PyObject *res = func(arg);
    _PySpec_LeaveNoPython(tstate, saved);
    return res;
}

/* Whether meth (an ml_meth of tp) is a class method of tp. */
static inline int
_PySpec_IsClassMethod(PyTypeObject *tp, PyCFunction meth)
{
    for (PyMethodDef *def = tp->tp_methods; def && def->ml_name; def++) {
        if (def->ml_meth == meth) {
            return (def->ml_flags & METH_CLASS) != 0;
        }
    }
    return 0;
}

/* The facts of method meth (the ml_meth of a method of tp) called with
 * nargs arguments, the first of exact type arg_type (NULL when unknown);
 * an entry specialized for arg_type is preferred over the generic one.
 *
 * self is the object the method is bound to, or NULL when not known (or
 * for a method called through its descriptor).  A subclass shares the
 * ml_meth of a class method: Sub.fromhex is bytes_fromhex bound to Sub,
 * and calls Sub(result).  So the entries of a class method specialized
 * for arg_type hold only when self is exactly tp; otherwise only the
 * generic entry, derived for any class, is returned. */
static inline const _PySpecCall *
_PySpec_FindMethod(PyTypeObject *tp, PyCFunction meth, PyObject *self,
                   int nargs, PyTypeObject *arg_type)
{
    const _PySpecCallTable *table = _PySpec_GetCallTable(tp);
    if (table == NULL) {
        return NULL;
    }
    if (self != (PyObject *)tp && _PySpec_IsClassMethod(tp, meth)) {
        arg_type = NULL;
    }
    const _PySpecCall *generic = NULL;
    for (Py_ssize_t i = 0; i < table->nmethods; i++) {
        const _PySpecCall *call = &table->methods[i];
        if (call->func.meth != meth || call->nargs != nargs) {
            continue;
        }
        if (call->arg_type == NULL) {
            generic = call;
        }
        else if (call->arg_type == arg_type) {
            return call;
        }
    }
    return generic;
}

#ifdef __cplusplus
}
#endif
#endif /* !Py_INTERNAL_PYSPEC_H */
