// This file is generated by Argument Clinic (Tools/clinic/libclinic/pyspec/
// call_table.py) from the specs of the core C files.  Do not edit: run
// clinic on a spec'd C file ("make clinic").

#ifndef Py_INTERNAL_PYSPEC_REGISTRY_H
#define Py_INTERNAL_PYSPEC_REGISTRY_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

/* The call tables (_PySpecCallTable: pycore_pyspec.h, which includes this
 * file), and _PySpec_REGISTRY(X), which is X(table) for each. */
/* Objects/pyspec/bytesobject.py */
// Export for '_testinternalcapi' shared extension
PyAPI_DATA(const _PySpecCallTable) _PySpec_bytes_calls;
// Export for '_testinternalcapi' shared extension
PyAPI_DATA(const _PySpecCallTable) _PySpec_bytes_iterator_calls;
#define _PySpec_REGISTRY(X) \
    X(_PySpec_bytes_calls) \
    X(_PySpec_bytes_iterator_calls)

#ifdef __cplusplus
}
#endif
#endif  // !Py_INTERNAL_PYSPEC_REGISTRY_H
