/*[pyspec]
Generated by Argument Clinic from Objects/pyspec/bytesobject.py.
Do not edit; edit the spec and run "make clinic".
[pyspec]*/

static PyObject *bytes_new_impl(PyTypeObject *cls, PyObject *source, const char *encoding, const char *errors);
static PyObject *bytes___bytes___impl(PyBytesObject *self);
static PyObject *bytes_fromhex_impl(PyTypeObject *cls, PyObject *string);
static PyObject *bytes_from_iterator(PyObject *it, PyObject *x);
static PyObject *bytes_from_iterator_list(PyObject *x);
static PyObject *bytes_from_iterator_tuple(PyObject *x);
static PyObject *bytes_from_iterator_list_lock_held(PyObject *x);

static PyObject *
bytes_new_impl(PyTypeObject *cls, PyObject *source, const char *encoding, const char *errors)
{
    PyObject *value = NULL;

    if (cls != &PyBytes_Type) {
        value = bytes_new_impl(&PyBytes_Type, source, encoding, errors);
        if (value == NULL) {
            return NULL;
        }
        {
            PyObject *_return_value = bytes_subtype_new(cls, value);
            Py_XDECREF(value);
            return _return_value;
        }
    }
    if (source == NULL) {
        if (encoding != NULL) {
            PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
            return NULL;
        }
        if (errors != NULL) {
            PyErr_SetString(PyExc_TypeError, "errors without a string argument");
            return NULL;
        }
        return Py_GetConstant(Py_CONSTANT_EMPTY_BYTES);
    }
    if (encoding != NULL) {
        if (!PyUnicode_Check(source)) {
            PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
            return NULL;
        }
        return PyUnicode_AsEncodedString(source, encoding, errors);
    }
    if (errors != NULL) {
        if (PyUnicode_Check(source)) {
            PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
            return NULL;
        }
        PyErr_SetString(PyExc_TypeError, "errors without a string argument");
        return NULL;
    }
    return bytes_new_nargs1(source);
}

static PyObject *
bytes___bytes___impl(PyBytesObject *self)
{
    if (PyBytes_CheckExact(self)) {
        return Py_NewRef(self);
    }
    return bytes_copy((PyObject *)self);
}

static PyObject *
bytes_fromhex_impl(PyTypeObject *cls, PyObject *string)
{
    PyObject *result = NULL;

    result = _PyBytes_FromHex(string, 0);
    if (result == NULL) {
        return NULL;
    }
    if (cls != &PyBytes_Type) {
        {
            PyObject *_return_value = PyObject_CallOneArg((PyObject *)cls, result);
            Py_XDECREF(result);
            return _return_value;
        }
    }
    return result;
}

PyObject *
PyBytes_FromObject(PyObject *x)
{
    PyObject *it = NULL;

    if (x == NULL) {
        PyErr_BadInternalCall();
        return NULL;
    }
    if (PyBytes_CheckExact(x)) {
        return Py_NewRef(x);
    }
    if (PyObject_CheckBuffer(x)) {
        return _PyBytes_FromBuffer(x);
    }
    if (!PyUnicode_Check(x)) {
        if (PyList_CheckExact(x)) {
            return bytes_from_iterator_list(x);
        }
        else {
            if (PyTuple_CheckExact(x)) {
                return bytes_from_iterator_tuple(x);
            }
            else {
                it = PyObject_GetIter(x);
                if (it == NULL) {
                    if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                        PyErr_Clear();
                    }
                    else {
                        return NULL;
                    }
                }
                else {
                    {
                        PyObject *_return_value = bytes_from_iterator(it, x);
                        Py_XDECREF(it);
                        return _return_value;
                    }
                }
            }
        }
    }
    PyErr_Format(PyExc_TypeError, "cannot convert '%.200s' object to bytes", Py_TYPE(x)->tp_name);
    return NULL;
}

static PyObject *
bytes_from_iterator(PyObject *it, PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyObject_LengthHint(x, 64);
    if (size == -1 && PyErr_Occurred()) {
        return NULL;
    }
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    for (;;) {
        item = PyIter_Next(it);
        if (item == NULL) {
            if (PyErr_Occurred()) {
                bytes_appender_discard(&writer);
                return NULL;
            }
            break;
        }
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((const PyLongObject *)item)) {
            value = _PyLong_CompactValue((const PyLongObject *)item);
            Py_DECREF(item);
        }
        else {
            value = PyNumber_AsSsize_t(item, NULL);
            Py_DECREF(item);
            if (value == -1 && PyErr_Occurred()) {
                bytes_appender_discard(&writer);
                return NULL;
            }
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            bytes_appender_discard(&writer);
            return NULL;
        }
        if (bytes_appender_append(&writer, value) < 0) {
            bytes_appender_discard(&writer);
            return NULL;
        }
    }
    {
        PyObject *_return_value = bytes_appender_finish(&writer);
        bytes_appender_discard(&writer);
        return _return_value;
    }
}

/* bytes_new() for exactly bytes with 0 positional argument(s):
 * return b''
 */
static PyObject *
bytes_new_nargs0(void)
{
    return Py_GetConstant(Py_CONSTANT_EMPTY_BYTES);
}

/* bytes_new() for exactly bytes with 1 positional argument(s):
 * if type(source) is bytes:
 *     return source
 * if (func := _PyObject_LookupSpecial(source, '__bytes__')) is not NULL:
 *     result = func()
 *     if not isinstance(result, bytes):
 *         raise TypeError(f'{fqname(type(source))}.__bytes__() must return a bytes, not {fqname(type(result))}')
 *     return result
 * if isinstance(source, str):
 *     raise TypeError('string argument without an encoding')
 * if hasattr(type(source), '__index__'):
 *     try:
 *         size = PyNumber_AsSsize_t(source, OverflowError)
 *     except TypeError:
 *         return PyBytes_FromObject(source)
 *     if size < 0:
 *         raise ValueError('negative count')
 *     return _PyBytes_FromSize(size, True)
 * if hasattr(type(source), '__buffer__'):
 *     return _PyBytes_FromBuffer(source)
 * if not isinstance(source, str):
 *     if type(source) is list:
 *         return bytes_from_iterator_list(source)
 *     elif type(source) is tuple:
 *         return bytes_from_iterator_tuple(source)
 *     else:
 *         try:
 *             it_1 = iter(source)
 *         except TypeError:
 *             pass
 *         else:
 *             return bytes_from_iterator(it_1, source)
 * raise TypeError(f"cannot convert '{tp_name(type(source))}' object to bytes")
 */
static PyObject *
bytes_new_nargs1(PyObject *source)
{
    PyObject *result = NULL;
    PyObject *func = NULL;
    Py_ssize_t size;
    PyObject *it_1 = NULL;

    if (PyBytes_CheckExact(source)) {
        return Py_NewRef(source);
    }
    func = _PyObject_LookupSpecial(source, &_Py_ID(__bytes__));
    if (func == NULL && PyErr_Occurred()) {
        return NULL;
    }
    if (func != NULL) {
        result = _PyObject_CallNoArgs(func);
        if (result == NULL) {
            Py_XDECREF(func);
            return NULL;
        }
        if (!PyBytes_Check(result)) {
            PyErr_Format(PyExc_TypeError, "%T.__bytes__() must return a bytes, not %T", source, result);
            Py_XDECREF(result);
            Py_XDECREF(func);
            return NULL;
        }
        Py_XDECREF(func);
        return result;
    }
    if (PyUnicode_Check(source)) {
        PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
        return NULL;
    }
    if (_PyIndex_Check(source)) {
        size = PyNumber_AsSsize_t(source, PyExc_OverflowError);
        if (size == -1 && PyErr_Occurred()) {
            if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                PyErr_Clear();
                return PyBytes_FromObject(source);
            }
            else {
                return NULL;
            }
        }
        if (size < 0) {
            PyErr_SetString(PyExc_ValueError, "negative count");
            return NULL;
        }
        return _PyBytes_FromSize(size, 1);
    }
    if (PyObject_CheckBuffer(source)) {
        return _PyBytes_FromBuffer(source);
    }
    if (!PyUnicode_Check(source)) {
        if (PyList_CheckExact(source)) {
            return bytes_from_iterator_list(source);
        }
        else {
            if (PyTuple_CheckExact(source)) {
                return bytes_from_iterator_tuple(source);
            }
            else {
                it_1 = PyObject_GetIter(source);
                if (it_1 == NULL) {
                    if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                        PyErr_Clear();
                    }
                    else {
                        return NULL;
                    }
                }
                else {
                    {
                        PyObject *_return_value = bytes_from_iterator(it_1, source);
                        Py_XDECREF(it_1);
                        return _return_value;
                    }
                }
            }
        }
    }
    PyErr_Format(PyExc_TypeError, "cannot convert '%.200s' object to bytes", Py_TYPE(source)->tp_name);
    return NULL;
}

/* bytes_new() for exactly bytes with 2 positional argument(s):
 * if not isinstance(source, str):
 *     raise TypeError('encoding without a string argument')
 * return PyUnicode_AsEncodedString(source, encoding, errors)
 */
static PyObject *
bytes_new_nargs2(PyObject *source, const char *encoding)
{
    if (!PyUnicode_Check(source)) {
        PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
        return NULL;
    }
    return PyUnicode_AsEncodedString(source, encoding, NULL);
}

/* bytes_new() for exactly bytes with 3 positional argument(s):
 * if not isinstance(source, str):
 *     raise TypeError('encoding without a string argument')
 * return PyUnicode_AsEncodedString(source, encoding, errors)
 */
static PyObject *
bytes_new_nargs3(PyObject *source, const char *encoding, const char *errors)
{
    if (!PyUnicode_Check(source)) {
        PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
        return NULL;
    }
    return PyUnicode_AsEncodedString(source, encoding, errors);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type bytes
 * (result is argument 0 (source); result is exactly bytes; runs no Python code):
 * return source
 */
static PyObject *
bytes_new_nargs1_bytes(PyObject *source)
{
    return Py_NewRef(source);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type bytearray
 * (result is exactly bytes; runs no Python code):
 * return _PyBytes_FromBuffer(source)
 */
static PyObject *
bytes_new_nargs1_bytearray(PyObject *source)
{
    return _PyBytes_FromBuffer(source);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type int
 * (result is exactly bytes; runs no Python code):
 * if _PyLong_IsCompact(source):
 *     size = _PyLong_CompactValue(source)
 * else:
 *     size = PyNumber_AsSsize_t(source, OverflowError)
 * if size < 0:
 *     raise ValueError('negative count')
 * return _PyBytes_FromSize(size, True)
 */
static PyObject *
bytes_new_nargs1_int(PyObject *source)
{
    Py_ssize_t size;

    if (_PyLong_IsCompact((const PyLongObject *)source)) {
        size = _PyLong_CompactValue((const PyLongObject *)source);
    }
    else {
        size = PyNumber_AsSsize_t(source, PyExc_OverflowError);
        if (size == -1 && PyErr_Occurred()) {
            return NULL;
        }
    }
    if (size < 0) {
        PyErr_SetString(PyExc_ValueError, "negative count");
        return NULL;
    }
    return _PyBytes_FromSize(size, 1);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type str
 * (always raises; runs no Python code):
 * raise TypeError('string argument without an encoding')
 */
static PyObject *
bytes_new_nargs1_str(PyObject *source)
{
    PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
    return NULL;
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type range
 * (result is exactly bytes; runs no Python code):
 * it_1 = iter(source)
 * return bytes_from_iterator(it_1, source)
 */
static PyObject *
bytes_new_nargs1_range(PyObject *source)
{
    PyObject *it_1 = NULL;

    it_1 = PyObject_GetIter(source);
    if (it_1 == NULL) {
        return NULL;
    }
    {
        PyObject *_return_value = bytes_from_iterator(it_1, source);
        Py_XDECREF(it_1);
        return _return_value;
    }
}

/* Call table of bytes() for the tier-2 optimizer, see
 * Include/internal/pycore_pyspec.h.  Generated by Argument Clinic
 * (Tools/clinic/libclinic/pyspec/call_table.py). */
static const _PySpecCall bytes_new_spec_calls[] = {
    /* bytes(): always Py_CONSTANT_EMPTY_BYTES, no side effects; runs no Python code */
    {
        .nargs = 0,
        .flags = 0,
        .result_const = Py_CONSTANT_EMPTY_BYTES,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = &PyBytes_Type,
        .func.f0 = bytes_new_nargs0,
    },
    /* bytes(bytes): result is argument 0 (source); result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = 0,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytes,
    },
    /* bytes(bytearray): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyByteArray_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytearray,
    },
    /* bytes(memoryview): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyMemoryView_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytearray,
    },
    /* bytes(list): result is exactly bytes; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyList_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_from_iterator_list,
    },
    /* bytes(tuple): result is exactly bytes; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyTuple_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_from_iterator_tuple,
    },
    /* bytes(int): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyLong_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_int,
    },
    /* bytes(str): always raises; runs no Python code */
    {
        .nargs = 1,
        .flags = _PySpec_ALWAYS_RAISES,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyUnicode_Type,
        .result_type = NULL,
        .func.f1 = bytes_new_nargs1_str,
    },
    /* bytes(range): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyRange_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_range,
    },
    /* bytes(x): result type not known exactly; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = NULL,
        .func.f1 = bytes_new_nargs1,
    },
};

/* Facts of the bytes methods implemented by the spec, for the tier-2
 * optimizer, keyed by ml_meth (see Include/internal/pycore_pyspec.h). */
static const _PySpecCall bytes_spec_methods[] = {
    /* bytes.__bytes__(bytes): result is argument 0 (self); result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = 0,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes___bytes__,
    },
    /* bytes.__bytes__(x): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes___bytes__,
    },
    /* bytes.fromhex(bytes), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(bytearray), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyByteArray_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(memoryview), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyMemoryView_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(list), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyList_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(tuple), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyTuple_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(int), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyLong_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(str), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyUnicode_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(range), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyRange_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(x): result type not known exactly; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = NULL,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
};

const _PySpecCallTable _PySpec_bytes_calls = {
    .type = &PyBytes_Type,
    .ncalls = Py_ARRAY_LENGTH(bytes_new_spec_calls),
    .calls = bytes_new_spec_calls,
    .nmethods = Py_ARRAY_LENGTH(bytes_spec_methods),
    .methods = bytes_spec_methods,
};

/* bytes_from_iterator() for it = iter(x), x of exact type list:
 * with critical_section(x):
 *     result = bytes_from_iterator_list_lock_held(x)
 * if result is not FALLBACK:
 *     return result
 * it = iter(x)
 * return bytes_from_iterator(it, x)
 */
static PyObject *
bytes_from_iterator_list(PyObject *x)
{
    PyObject *result = NULL;
    PyObject *it = NULL;

    Py_BEGIN_CRITICAL_SECTION(x);
    result = bytes_from_iterator_list_lock_held(x);
    Py_END_CRITICAL_SECTION();
    if (result == NULL) {
        return NULL;
    }
    if (result != Py_None) {
        return result;
    }
    it = PyObject_GetIter(x);
    if (it == NULL) {
        return NULL;
    }
    {
        PyObject *_return_value = bytes_from_iterator(it, x);
        Py_XDECREF(it);
        return _return_value;
    }
}

/* bytes_from_iterator() for it = iter(x), x of exact type tuple:
 * size = len(x)
 * writer = bytes_appender_init(size)
 * try:
 *     for item in x:
 *         if (type(item) is int or type(item) is bool) and _PyLong_IsCompact(item):
 *             value = _PyLong_CompactValue(item)
 *         else:
 *             value = PyNumber_AsSsize_t(item, NULL)
 *         if value < 0 or value >= 256:
 *             raise ValueError('bytes must be in range(0, 256)')
 *         bytes_appender_append_unchecked(writer, value)
 *     return bytes_appender_finish(writer)
 * finally:
 *     bytes_appender_discard(writer)
 */
static PyObject *
bytes_from_iterator_tuple(PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyTuple_GET_SIZE(x);
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    for (Py_ssize_t item_index = 0, item_count = PyTuple_GET_SIZE(x); item_index < item_count; item_index++) {
        item = PyTuple_GET_ITEM(x, item_index);
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((const PyLongObject *)item)) {
            value = _PyLong_CompactValue((const PyLongObject *)item);
        }
        else {
            value = PyNumber_AsSsize_t(item, NULL);
            if (value == -1 && PyErr_Occurred()) {
                bytes_appender_discard(&writer);
                return NULL;
            }
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            bytes_appender_discard(&writer);
            return NULL;
        }
        bytes_appender_append_unchecked(&writer, value);
    }
    {
        PyObject *_return_value = bytes_appender_finish(&writer);
        bytes_appender_discard(&writer);
        return _return_value;
    }
}

/* bytes_from_iterator() for it = iter(x), x of exact type list, the snapshot: called in the critical section of x, runs no Python code; FALLBACK (Py_None) when that could run Python code:
 * size = len(x)
 * writer = bytes_appender_init(size)
 * try:
 *     for item in x:
 *         if (type(item) is int or type(item) is bool) and _PyLong_IsCompact(item):
 *             value = _PyLong_CompactValue(item)
 *         else:
 *             return FALLBACK
 *         if value < 0 or value >= 256:
 *             raise ValueError('bytes must be in range(0, 256)')
 *         bytes_appender_append_unchecked(writer, value)
 *     return bytes_appender_finish(writer)
 * finally:
 *     bytes_appender_discard(writer)
 */
static PyObject *
bytes_from_iterator_list_lock_held(PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyList_GET_SIZE(x);
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    PyObject **item_items = _PyList_ITEMS(x);
    for (Py_ssize_t item_index = 0, item_count = PyList_GET_SIZE(x); item_index < item_count; item_index++) {
        item = item_items[item_index];
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((const PyLongObject *)item)) {
            value = _PyLong_CompactValue((const PyLongObject *)item);
        }
        else {
            bytes_appender_discard(&writer);
            return Py_None;
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            bytes_appender_discard(&writer);
            return NULL;
        }
        bytes_appender_append_unchecked(&writer, value);
    }
    {
        PyObject *_return_value = bytes_appender_finish(&writer);
        bytes_appender_discard(&writer);
        return _return_value;
    }
}


/* bytes */

PyDoc_STRVAR(bytes__doc__,
"bytes(iterable_of_ints) -> bytes\n"
"bytes(string, encoding[, errors]) -> bytes\n"
"bytes(bytes_or_buffer) -> immutable copy of bytes_or_buffer\n"
"bytes(int) -> bytes object of size given by the parameter initialized with null bytes\n"
"bytes() -> empty bytes object\n"
"\n"
"Construct an immutable array of bytes from:\n"
"  - an iterable yielding integers in range(256)\n"
"  - a text string encoded using the specified encoding\n"
"  - any object implementing the buffer API.\n"
"  - an integer");

PyDoc_STRVAR(bytes_capitalize__doc__,
"B.capitalize() -> copy of B\n"
"\n"
"Return a copy of B with only its first character capitalized (ASCII)\n"
"and the rest lower-cased.");

PyDoc_STRVAR(bytes_isalnum__doc__,
"B.isalnum() -> bool\n"
"\n"
"Return True if all characters in B are alphanumeric\n"
"and there is at least one character in B, False otherwise.");

PyDoc_STRVAR(bytes_isalpha__doc__,
"B.isalpha() -> bool\n"
"\n"
"Return True if all characters in B are alphabetic\n"
"and there is at least one character in B, False otherwise.");

PyDoc_STRVAR(bytes_isascii__doc__,
"B.isascii() -> bool\n"
"\n"
"Return True if B is empty or all characters in B are ASCII,\n"
"False otherwise.");

PyDoc_STRVAR(bytes_isdigit__doc__,
"B.isdigit() -> bool\n"
"\n"
"Return True if all characters in B are digits\n"
"and there is at least one character in B, False otherwise.");

PyDoc_STRVAR(bytes_islower__doc__,
"B.islower() -> bool\n"
"\n"
"Return True if all cased characters in B are lowercase and there is\n"
"at least one cased character in B, False otherwise.");

PyDoc_STRVAR(bytes_isspace__doc__,
"B.isspace() -> bool\n"
"\n"
"Return True if all characters in B are whitespace\n"
"and there is at least one character in B, False otherwise.");

PyDoc_STRVAR(bytes_istitle__doc__,
"B.istitle() -> bool\n"
"\n"
"Return True if B is a titlecased string and there is at least one\n"
"character in B, i.e. uppercase characters may only follow uncased\n"
"characters and lowercase characters only cased ones. Return False\n"
"otherwise.");

PyDoc_STRVAR(bytes_isupper__doc__,
"B.isupper() -> bool\n"
"\n"
"Return True if all cased characters in B are uppercase and there is\n"
"at least one cased character in B, False otherwise.");

PyDoc_STRVAR(bytes_lower__doc__,
"B.lower() -> copy of B\n"
"\n"
"Return a copy of B with all ASCII characters converted to lowercase.");

PyDoc_STRVAR(bytes_swapcase__doc__,
"B.swapcase() -> copy of B\n"
"\n"
"Return a copy of B with uppercase ASCII characters converted\n"
"to lowercase ASCII and vice versa.");

PyDoc_STRVAR(bytes_title__doc__,
"B.title() -> copy of B\n"
"\n"
"Return a titlecased version of B, i.e. ASCII words start with\n"
"uppercase characters, all remaining cased characters have lowercase.");

PyDoc_STRVAR(bytes_upper__doc__,
"B.upper() -> copy of B\n"
"\n"
"Return a copy of B with all ASCII characters converted to uppercase.");

static PyMethodDef bytes_methods[] = {
    {"__getnewargs__", bytes_getnewargs, METH_NOARGS, NULL},
    BYTES___BYTES___METHODDEF
    {"capitalize", stringlib_capitalize, METH_NOARGS, bytes_capitalize__doc__},
    STRINGLIB_CENTER_METHODDEF
    BYTES_COUNT_METHODDEF
    BYTES_DECODE_METHODDEF
    BYTES_ENDSWITH_METHODDEF
    STRINGLIB_EXPANDTABS_METHODDEF
    BYTES_FIND_METHODDEF
    BYTES_FROMHEX_METHODDEF
    BYTES_HEX_METHODDEF
    BYTES_INDEX_METHODDEF
    {"isalnum", stringlib_isalnum, METH_NOARGS, bytes_isalnum__doc__},
    {"isalpha", stringlib_isalpha, METH_NOARGS, bytes_isalpha__doc__},
    {"isascii", stringlib_isascii, METH_NOARGS, bytes_isascii__doc__},
    {"isdigit", stringlib_isdigit, METH_NOARGS, bytes_isdigit__doc__},
    {"islower", stringlib_islower, METH_NOARGS, bytes_islower__doc__},
    {"isspace", stringlib_isspace, METH_NOARGS, bytes_isspace__doc__},
    {"istitle", stringlib_istitle, METH_NOARGS, bytes_istitle__doc__},
    {"isupper", stringlib_isupper, METH_NOARGS, bytes_isupper__doc__},
    BYTES_JOIN_METHODDEF
    STRINGLIB_LJUST_METHODDEF
    {"lower", stringlib_lower, METH_NOARGS, bytes_lower__doc__},
    BYTES_LSTRIP_METHODDEF
    BYTES_MAKETRANS_METHODDEF
    BYTES_PARTITION_METHODDEF
    BYTES_REPLACE_METHODDEF
    BYTES_REMOVEPREFIX_METHODDEF
    BYTES_REMOVESUFFIX_METHODDEF
    BYTES_RFIND_METHODDEF
    BYTES_RINDEX_METHODDEF
    STRINGLIB_RJUST_METHODDEF
    BYTES_RPARTITION_METHODDEF
    BYTES_RSPLIT_METHODDEF
    BYTES_RSTRIP_METHODDEF
    BYTES_SPLIT_METHODDEF
    BYTES_SPLITLINES_METHODDEF
    BYTES_STARTSWITH_METHODDEF
    BYTES_STRIP_METHODDEF
    {"swapcase", stringlib_swapcase, METH_NOARGS, bytes_swapcase__doc__},
    {"title", stringlib_title, METH_NOARGS, bytes_title__doc__},
    BYTES_TRANSLATE_METHODDEF
    {"upper", stringlib_upper, METH_NOARGS, bytes_upper__doc__},
    STRINGLIB_ZFILL_METHODDEF
    {NULL, NULL}  /* sentinel */
};

static PyNumberMethods bytes_as_number = {
    .nb_remainder = bytes_mod,
};

static PySequenceMethods bytes_as_sequence = {
    .sq_length = bytes_length,
    .sq_concat = _PyBytes_Concat,
    .sq_repeat = _PyBytes_Repeat,
    .sq_item = bytes_item,
    .sq_contains = bytes_contains,
};

static PyMappingMethods bytes_as_mapping = {
    .mp_length = bytes_length,
    .mp_subscript = bytes_subscript,
};

static PyBufferProcs bytes_as_buffer = {
    .bf_getbuffer = bytes_buffer_getbuffer,
};

PyTypeObject PyBytes_Type = {
    PyVarObject_HEAD_INIT(&PyType_Type, 0)
    .tp_name = "bytes",
    .tp_basicsize = PyBytesObject_SIZE,
    .tp_itemsize = sizeof(char),
    .tp_dealloc = bytes_dealloc,
    .tp_repr = bytes_repr,
    .tp_as_number = &bytes_as_number,
    .tp_as_sequence = &bytes_as_sequence,
    .tp_as_mapping = &bytes_as_mapping,
    .tp_hash = bytes_hash,
    .tp_str = bytes_str,
    .tp_as_buffer = &bytes_as_buffer,
    .tp_flags = Py_TPFLAGS_DEFAULT |
        Py_TPFLAGS_BASETYPE |
        Py_TPFLAGS_BYTES_SUBCLASS | _Py_TPFLAGS_MATCH_SELF,
    .tp_doc = bytes__doc__,
    .tp_richcompare = bytes_richcompare,
    .tp_iter = bytes_iter,
    .tp_methods = bytes_methods,
    .tp_alloc = bytes_alloc,
    .tp_new = bytes_new,
    .tp_free = PyObject_Free,
    .tp_version_tag = _Py_TYPE_VERSION_BYTES,
    .tp_vectorcall = bytes_vectorcall,
    ._tp_iteritem = bytes_iteritem,
};

/* bytes_iterator */

PyDoc_STRVAR(bytes_iterator___length_hint____doc__,
"Private method returning an estimate of len(list(it)).");

PyDoc_STRVAR(bytes_iterator___reduce____doc__,
"Return state information for pickling.");

PyDoc_STRVAR(bytes_iterator___setstate____doc__,
"Set state information for unpickling.");

static PyMethodDef bytes_iterator_methods[] = {
    {"__length_hint__", striter_len, METH_NOARGS, bytes_iterator___length_hint____doc__},
    {"__reduce__", striter_reduce, METH_NOARGS, bytes_iterator___reduce____doc__},
    {"__setstate__", striter_setstate, METH_O, bytes_iterator___setstate____doc__},
    {NULL, NULL}  /* sentinel */
};

PyTypeObject PyBytesIter_Type = {
    PyVarObject_HEAD_INIT(&PyType_Type, 0)
    .tp_name = "bytes_iterator",
    .tp_basicsize = sizeof(striterobject),
    .tp_dealloc = striter_dealloc,
    .tp_flags = Py_TPFLAGS_DEFAULT |
        Py_TPFLAGS_HAVE_GC,
    .tp_traverse = striter_traverse,
    .tp_iter = PyObject_SelfIter,
    .tp_iternext = striter_next,
    .tp_methods = bytes_iterator_methods,
};
