/*[pyspec]
Generated by Argument Clinic from Objects/pyspec/bytesobject.py.
Do not edit; edit the spec and run "make clinic".
[pyspec]*/

static PyObject *bytes_new_impl(PyTypeObject *cls, PyObject *source, const char *encoding, const char *errors);
static PyObject *bytes___bytes___impl(PyBytesObject *self);
static PyObject *bytes_fromhex_impl(PyTypeObject *cls, PyObject *string);
static PyObject *bytes_from_iterator(PyObject *it, PyObject *x);
static PyObject *bytes_from_iterator_list(PyObject *x);
static PyObject *bytes_from_iterator_tuple(PyObject *x);
static PyObject *bytes_from_iterator_list_lock_held(PyObject *x);

static PyObject *
bytes_new_impl(PyTypeObject *cls, PyObject *source, const char *encoding, const char *errors)
{
    PyObject *value = NULL;

    if (cls != &PyBytes_Type) {
        value = bytes_new_impl(&PyBytes_Type, source, encoding, errors);
        if (value == NULL) {
            return NULL;
        }
        {
            PyObject *_return_value = bytes_subtype_new(cls, value);
            Py_XDECREF(value);
            return _return_value;
        }
    }
    if (source == NULL) {
        if (encoding != NULL) {
            PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
            return NULL;
        }
        if (errors != NULL) {
            PyErr_SetString(PyExc_TypeError, "errors without a string argument");
            return NULL;
        }
        return Py_GetConstant(Py_CONSTANT_EMPTY_BYTES);
    }
    if (encoding != NULL) {
        if (!PyUnicode_Check(source)) {
            PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
            return NULL;
        }
        return PyUnicode_AsEncodedString(source, encoding, errors);
    }
    if (errors != NULL) {
        if (PyUnicode_Check(source)) {
            PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
            return NULL;
        }
        PyErr_SetString(PyExc_TypeError, "errors without a string argument");
        return NULL;
    }
    return bytes_new_nargs1(source);
}

static PyObject *
bytes___bytes___impl(PyBytesObject *self)
{
    if (PyBytes_CheckExact(self)) {
        return Py_NewRef(self);
    }
    return PyBytes_FromStringAndSize(PyBytes_AS_STRING(self), PyBytes_GET_SIZE(self));
}

static PyObject *
bytes_fromhex_impl(PyTypeObject *cls, PyObject *string)
{
    PyObject *result = NULL;

    result = _PyBytes_FromHex(string, 0);
    if (result == NULL) {
        return NULL;
    }
    if (cls != &PyBytes_Type) {
        {
            PyObject *_return_value = PyObject_CallOneArg((PyObject *)cls, result);
            Py_XDECREF(result);
            return _return_value;
        }
    }
    return result;
}

PyObject *
PyBytes_FromObject(PyObject *x)
{
    PyObject *it = NULL;

    if (x == NULL) {
        PyErr_BadInternalCall();
        return NULL;
    }
    if (PyBytes_CheckExact(x)) {
        return Py_NewRef(x);
    }
    if (PyObject_CheckBuffer(x)) {
        return _PyBytes_FromBuffer(x);
    }
    if (!PyUnicode_Check(x)) {
        if (PyList_CheckExact(x)) {
            return bytes_from_iterator_list(x);
        }
        else {
            if (PyTuple_CheckExact(x)) {
                return bytes_from_iterator_tuple(x);
            }
            else {
                it = PyObject_GetIter(x);
                if (it == NULL) {
                    if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                        PyErr_Clear();
                    }
                    else {
                        return NULL;
                    }
                }
                else {
                    {
                        PyObject *_return_value = bytes_from_iterator(it, x);
                        Py_XDECREF(it);
                        return _return_value;
                    }
                }
            }
        }
    }
    PyErr_Format(PyExc_TypeError, "cannot convert '%.200s' object to bytes", Py_TYPE(x)->tp_name);
    return NULL;
}

static PyObject *
bytes_from_iterator(PyObject *it, PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyObject_LengthHint(x, 64);
    if (size == -1 && PyErr_Occurred()) {
        return NULL;
    }
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    for (;;) {
        item = PyIter_Next(it);
        if (item == NULL) {
            if (PyErr_Occurred()) {
                PyBytesWriter_Discard(writer.writer);
                return NULL;
            }
            break;
        }
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((PyLongObject *)item)) {
            value = _PyLong_CompactValue((PyLongObject *)item);
            Py_DECREF(item);
        }
        else {
            value = PyNumber_AsSsize_t(item, NULL);
            Py_DECREF(item);
            if (value == -1 && PyErr_Occurred()) {
                PyBytesWriter_Discard(writer.writer);
                return NULL;
            }
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            PyBytesWriter_Discard(writer.writer);
            return NULL;
        }
        if (bytes_appender_append(&writer, (unsigned char)value) < 0) {
            PyBytesWriter_Discard(writer.writer);
            return NULL;
        }
    }
    return PyBytesWriter_FinishWithPointer(writer.writer, writer.str);
}

/* bytes_new() for exactly bytes with 0 positional argument(s):
 * return b''
 */
static PyObject *
bytes_new_nargs0(void)
{
    return Py_GetConstant(Py_CONSTANT_EMPTY_BYTES);
}

/* bytes_new() for exactly bytes with 1 positional argument(s):
 * if type(source) is bytes:
 *     return source
 * else:
 *     if (func := C.lookup_special(source, '__bytes__')) is not NULL:
 *         result = func()
 *         if not isinstance(result, bytes):
 *             raise TypeError(f'{fqname(type(source))}.__bytes__() must return a bytes, not {fqname(type(result))}')
 *         return result
 *     if isinstance(source, str):
 *         raise TypeError('string argument without an encoding')
 *     if hasattr(type(source), '__index__'):
 *         try:
 *             size = C.PyNumber_AsSsize_t(source, OverflowError)
 *         except TypeError:
 *             return PyBytes_FromObject(source)
 *         if size < 0:
 *             raise ValueError('negative count')
 *         return C._PyBytes_FromSize(size, True)
 *     if hasattr(type(source), '__buffer__'):
 *         return C._PyBytes_FromBuffer(source)
 *     if not isinstance(source, str):
 *         if type(source) is list:
 *             return bytes_from_iterator_list(source)
 *         elif type(source) is tuple:
 *             return bytes_from_iterator_tuple(source)
 *         else:
 *             try:
 *                 it_1 = iter(source)
 *             except TypeError:
 *                 pass
 *             else:
 *                 return bytes_from_iterator(it_1, source)
 *     raise TypeError(f"cannot convert '{tp_name(type(source))}' object to bytes")
 */
static PyObject *
bytes_new_nargs1(PyObject *source)
{
    PyObject *result = NULL;
    PyObject *func = NULL;
    Py_ssize_t size;
    PyObject *it_1 = NULL;

    if (PyBytes_CheckExact(source)) {
        return Py_NewRef(source);
    }
    else {
        func = _PyObject_LookupSpecial(source, &_Py_ID(__bytes__));
        if (func == NULL && PyErr_Occurred()) {
            return NULL;
        }
        if (func != NULL) {
            result = _PyObject_CallNoArgs(func);
            if (result == NULL) {
                Py_XDECREF(func);
                return NULL;
            }
            if (!PyBytes_Check(result)) {
                PyErr_Format(PyExc_TypeError, "%T.__bytes__() must return a bytes, not %T", source, result);
                Py_XDECREF(result);
                Py_XDECREF(func);
                return NULL;
            }
            Py_XDECREF(func);
            return result;
        }
        if (PyUnicode_Check(source)) {
            PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
            return NULL;
        }
        if (_PyIndex_Check(source)) {
            size = PyNumber_AsSsize_t(source, PyExc_OverflowError);
            if (size == -1 && PyErr_Occurred()) {
                if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                    PyErr_Clear();
                    return PyBytes_FromObject(source);
                }
                else {
                    return NULL;
                }
            }
            if (size < 0) {
                PyErr_SetString(PyExc_ValueError, "negative count");
                return NULL;
            }
            return _PyBytes_FromSize(size, 1);
        }
        if (PyObject_CheckBuffer(source)) {
            return _PyBytes_FromBuffer(source);
        }
        if (!PyUnicode_Check(source)) {
            if (PyList_CheckExact(source)) {
                return bytes_from_iterator_list(source);
            }
            else {
                if (PyTuple_CheckExact(source)) {
                    return bytes_from_iterator_tuple(source);
                }
                else {
                    it_1 = PyObject_GetIter(source);
                    if (it_1 == NULL) {
                        if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                            PyErr_Clear();
                        }
                        else {
                            return NULL;
                        }
                    }
                    else {
                        {
                            PyObject *_return_value = bytes_from_iterator(it_1, source);
                            Py_XDECREF(it_1);
                            return _return_value;
                        }
                    }
                }
            }
        }
        PyErr_Format(PyExc_TypeError, "cannot convert '%.200s' object to bytes", Py_TYPE(source)->tp_name);
        return NULL;
    }
}

/* bytes_new() for exactly bytes with 2 positional argument(s):
 * if not isinstance(source, str):
 *     raise TypeError('encoding without a string argument')
 * return C.PyUnicode_AsEncodedString(source, encoding, errors)
 */
static PyObject *
bytes_new_nargs2(PyObject *source, const char *encoding)
{
    if (!PyUnicode_Check(source)) {
        PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
        return NULL;
    }
    return PyUnicode_AsEncodedString(source, encoding, NULL);
}

/* bytes_new() for exactly bytes with 3 positional argument(s):
 * if not isinstance(source, str):
 *     raise TypeError('encoding without a string argument')
 * return C.PyUnicode_AsEncodedString(source, encoding, errors)
 */
static PyObject *
bytes_new_nargs3(PyObject *source, const char *encoding, const char *errors)
{
    if (!PyUnicode_Check(source)) {
        PyErr_SetString(PyExc_TypeError, "encoding without a string argument");
        return NULL;
    }
    return PyUnicode_AsEncodedString(source, encoding, errors);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type bytes
 * (result is argument 0 (source); result is exactly bytes; runs no Python code):
 * return source
 */
static PyObject *
bytes_new_nargs1_bytes(PyObject *source)
{
    return Py_NewRef(source);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type bytearray
 * (result is exactly bytes; runs no Python code):
 * return C._PyBytes_FromBuffer(source)
 */
static PyObject *
bytes_new_nargs1_bytearray(PyObject *source)
{
    return _PyBytes_FromBuffer(source);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type int
 * (result is exactly bytes; may run Python code):
 * if C.PyNumber_AsSsize_t.fast(source):
 *     size = C.PyNumber_AsSsize_t(source, OverflowError)
 * else:
 *     try:
 *         size = C.PyNumber_AsSsize_t(source, OverflowError)
 *     except TypeError:
 *         return PyBytes_FromObject(source)
 * if size < 0:
 *     raise ValueError('negative count')
 * return C._PyBytes_FromSize(size, True)
 */
static PyObject *
bytes_new_nargs1_int(PyObject *source)
{
    Py_ssize_t size;

    if (_PyLong_IsCompact((PyLongObject *)source)) {
        size = _PyLong_CompactValue((PyLongObject *)source);
    }
    else {
        size = PyNumber_AsSsize_t(source, PyExc_OverflowError);
        if (size == -1 && PyErr_Occurred()) {
            if (PyErr_ExceptionMatches(PyExc_TypeError)) {
                PyErr_Clear();
                return PyBytes_FromObject(source);
            }
            else {
                return NULL;
            }
        }
    }
    if (size < 0) {
        PyErr_SetString(PyExc_ValueError, "negative count");
        return NULL;
    }
    return _PyBytes_FromSize(size, 1);
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type str
 * (always raises; runs no Python code):
 * raise TypeError('string argument without an encoding')
 */
static PyObject *
bytes_new_nargs1_str(PyObject *source)
{
    PyErr_SetString(PyExc_TypeError, "string argument without an encoding");
    return NULL;
}

/* bytes_new() for exactly bytes with 1 positional argument of exact type range
 * (result is exactly bytes; runs no Python code):
 * it_1 = iter(source)
 * return bytes_from_iterator(it_1, source)
 */
static PyObject *
bytes_new_nargs1_range(PyObject *source)
{
    PyObject *it_1 = NULL;

    it_1 = PyObject_GetIter(source);
    if (it_1 == NULL) {
        return NULL;
    }
    {
        PyObject *_return_value = bytes_from_iterator(it_1, source);
        Py_XDECREF(it_1);
        return _return_value;
    }
}

/* Call table of bytes() for the tier-2 optimizer, see
 * Include/internal/pycore_pyspec.h.  Generated by Argument Clinic
 * (Tools/clinic/libclinic/pyspec/call_table.py). */
static const _PySpecCall bytes_new_spec_calls[] = {
    /* bytes(): always Py_CONSTANT_EMPTY_BYTES, no side effects; runs no Python code */
    {
        .nargs = 0,
        .flags = 0,
        .result_const = Py_CONSTANT_EMPTY_BYTES,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = &PyBytes_Type,
        .func.f0 = bytes_new_nargs0,
    },
    /* bytes(bytes): result is argument 0 (source); result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = 0,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytes,
    },
    /* bytes(bytearray): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyByteArray_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytearray,
    },
    /* bytes(memoryview): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyMemoryView_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_bytearray,
    },
    /* bytes(list): result is exactly bytes; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyList_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_from_iterator_list,
    },
    /* bytes(tuple): result is exactly bytes; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyTuple_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_from_iterator_tuple,
    },
    /* bytes(int): result is exactly bytes; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyLong_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_int,
    },
    /* bytes(str): always raises; runs no Python code */
    {
        .nargs = 1,
        .flags = _PySpec_ALWAYS_RAISES,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyUnicode_Type,
        .result_type = NULL,
        .func.f1 = bytes_new_nargs1_str,
    },
    /* bytes(range): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyRange_Type,
        .result_type = &PyBytes_Type,
        .func.f1 = bytes_new_nargs1_range,
    },
    /* bytes(x): result type not known exactly; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = NULL,
        .func.f1 = bytes_new_nargs1,
    },
};

/* Facts of the bytes methods implemented by the spec, for the tier-2
 * optimizer, keyed by ml_meth (see Include/internal/pycore_pyspec.h). */
static const _PySpecCall bytes_spec_methods[] = {
    /* bytes.__bytes__(bytes): result is argument 0 (self); result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = 0,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes___bytes__,
    },
    /* bytes.__bytes__(x): result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes___bytes__,
    },
    /* bytes.fromhex(bytes), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyBytes_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(bytearray), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyByteArray_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(memoryview), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyMemoryView_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(list), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyList_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(tuple), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyTuple_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(int), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyLong_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(str), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyUnicode_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(range), on exactly bytes: result is exactly bytes; runs no Python code */
    {
        .nargs = 1,
        .flags = 0,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = &PyRange_Type,
        .result_type = &PyBytes_Type,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
    /* bytes.fromhex(x): result type not known exactly; may run Python code */
    {
        .nargs = 1,
        .flags = _PySpec_MAY_RUN_PYTHON,
        .result_const = -1,
        .result_alias = -1,
        .arg_type = NULL,
        .result_type = NULL,
        .func.meth = (PyCFunction)bytes_fromhex,
    },
};

const _PySpecCallTable _PySpec_bytes_calls = {
    .type = &PyBytes_Type,
    .ncalls = Py_ARRAY_LENGTH(bytes_new_spec_calls),
    .calls = bytes_new_spec_calls,
    .nmethods = Py_ARRAY_LENGTH(bytes_spec_methods),
    .methods = bytes_spec_methods,
};

/* bytes_from_iterator() for it = iter(x), x of exact type list:
 * with C.critical_section(x):
 *     result = bytes_from_iterator_list_lock_held(x)
 * if result is not FALLBACK:
 *     return result
 * it = iter(x)
 * return bytes_from_iterator(it, x)
 */
static PyObject *
bytes_from_iterator_list(PyObject *x)
{
    PyObject *result = NULL;
    PyObject *it = NULL;

    Py_BEGIN_CRITICAL_SECTION(x);
    result = bytes_from_iterator_list_lock_held(x);
    Py_END_CRITICAL_SECTION();
    if (result == NULL) {
        return NULL;
    }
    if (result != Py_None) {
        return result;
    }
    it = PyObject_GetIter(x);
    if (it == NULL) {
        return NULL;
    }
    {
        PyObject *_return_value = bytes_from_iterator(it, x);
        Py_XDECREF(it);
        return _return_value;
    }
}

/* bytes_from_iterator() for it = iter(x), x of exact type tuple:
 * size = C.PyObject_LengthHint(x, 64)
 * writer = C.bytes_appender(size)
 * for item in x:
 *     if C.PyNumber_AsSsize_t.fast(item):
 *         value = C.PyNumber_AsSsize_t(item, NULL)
 *     else:
 *         value = C.PyNumber_AsSsize_t(item, NULL)
 *     if value < 0 or value >= 256:
 *         raise ValueError('bytes must be in range(0, 256)')
 *     C.bytes_appender_append(writer, value)
 * return C.bytes_appender_finish(writer)
 */
static PyObject *
bytes_from_iterator_tuple(PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyTuple_GET_SIZE(x);
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    for (Py_ssize_t item_index = 0, item_count = PyTuple_GET_SIZE(x); item_index < item_count; item_index++) {
        item = PyTuple_GET_ITEM(x, item_index);
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((PyLongObject *)item)) {
            value = _PyLong_CompactValue((PyLongObject *)item);
        }
        else {
            value = PyNumber_AsSsize_t(item, NULL);
            if (value == -1 && PyErr_Occurred()) {
                PyBytesWriter_Discard(writer.writer);
                return NULL;
            }
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            PyBytesWriter_Discard(writer.writer);
            return NULL;
        }
        bytes_appender_append_unchecked(&writer, (unsigned char)value);
    }
    return PyBytesWriter_FinishWithPointer(writer.writer, writer.str);
}

/* bytes_from_iterator() for it = iter(x), x of exact type list, the snapshot: called in the critical section of x, runs no Python code; FALLBACK (Py_None) when that could run Python code:
 * size = C.PyObject_LengthHint(x, 64)
 * writer = C.bytes_appender(size)
 * for item in x:
 *     if C.PyNumber_AsSsize_t.fast(item):
 *         value = C.PyNumber_AsSsize_t(item, NULL)
 *     else:
 *         return FALLBACK
 *     if value < 0 or value >= 256:
 *         raise ValueError('bytes must be in range(0, 256)')
 *     C.bytes_appender_append(writer, value)
 * return C.bytes_appender_finish(writer)
 */
static PyObject *
bytes_from_iterator_list_lock_held(PyObject *x)
{
    Py_ssize_t size;
    bytes_appender writer;
    PyObject *item = NULL;
    Py_ssize_t value;

    size = PyList_GET_SIZE(x);
    if (bytes_appender_init(&writer, size) < 0) {
        return NULL;
    }
    PyObject **item_items = _PyList_ITEMS(x);
    for (Py_ssize_t item_index = 0, item_count = PyList_GET_SIZE(x); item_index < item_count; item_index++) {
        item = item_items[item_index];
        if ((PyLong_CheckExact(item) || PyBool_Check(item)) && _PyLong_IsCompact((PyLongObject *)item)) {
            value = _PyLong_CompactValue((PyLongObject *)item);
        }
        else {
            PyBytesWriter_Discard(writer.writer);
            return Py_None;
        }
        if ((value < 0) || (value >= 256)) {
            PyErr_SetString(PyExc_ValueError, "bytes must be in range(0, 256)");
            PyBytesWriter_Discard(writer.writer);
            return NULL;
        }
        bytes_appender_append_unchecked(&writer, (unsigned char)value);
    }
    return PyBytesWriter_FinishWithPointer(writer.writer, writer.str);
}

