/*[pyspec]
Generated by Argument Clinic from Objects/pyspec/bytearrayobject.py.
Do not edit; edit the spec and run "make clinic".
[pyspec]*/

/* bytearray */

PyDoc_STRVAR(bytearray__doc__,
"bytearray(iterable_of_ints) -> bytearray\n"
"bytearray(string, encoding[, errors]) -> bytearray\n"
"bytearray(bytes_or_buffer) -> mutable copy of bytes_or_buffer\n"
"bytearray(int) -> bytes array of size given by the parameter initialized with null bytes\n"
"bytearray() -> empty bytes array\n"
"\n"
"Construct a mutable bytearray object from:\n"
"  - an iterable yielding integers in range(256)\n"
"  - a text string encoded using the specified encoding\n"
"  - a bytes or a buffer object\n"
"  - any object implementing the buffer API.\n"
"  - an integer");

PyDoc_STRVAR(bytearray___alloc____doc__,
"B.__alloc__() -> int\n"
"\n"
"Return the number of bytes actually allocated.");

PyDoc_STRVAR(bytearray_capitalize__doc__,
"B.capitalize() -> copy of B\n"
"\n"
"Return a copy of B with only its first character capitalized (ASCII)\n"
"and the rest lower-cased.");

static PyObject *
bytearray_capitalize(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_capitalize(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyObject *
bytearray_center(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_center(self, args, nargs);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyObject *
bytearray_expandtabs(PyObject *self, PyObject *const *args, Py_ssize_t nargs, PyObject *kwnames)
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_expandtabs(self, args, nargs, kwnames);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isalnum__doc__,
"B.isalnum() -> bool\n"
"\n"
"Return True if all characters in B are alphanumeric\n"
"and there is at least one character in B, False otherwise.");

static PyObject *
bytearray_isalnum(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isalnum(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isalpha__doc__,
"B.isalpha() -> bool\n"
"\n"
"Return True if all characters in B are alphabetic\n"
"and there is at least one character in B, False otherwise.");

static PyObject *
bytearray_isalpha(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isalpha(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isascii__doc__,
"B.isascii() -> bool\n"
"\n"
"Return True if B is empty or all characters in B are ASCII,\n"
"False otherwise.");

static PyObject *
bytearray_isascii(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isascii(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isdigit__doc__,
"B.isdigit() -> bool\n"
"\n"
"Return True if all characters in B are digits\n"
"and there is at least one character in B, False otherwise.");

static PyObject *
bytearray_isdigit(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isdigit(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_islower__doc__,
"B.islower() -> bool\n"
"\n"
"Return True if all cased characters in B are lowercase and there is\n"
"at least one cased character in B, False otherwise.");

static PyObject *
bytearray_islower(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_islower(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isspace__doc__,
"B.isspace() -> bool\n"
"\n"
"Return True if all characters in B are whitespace\n"
"and there is at least one character in B, False otherwise.");

static PyObject *
bytearray_isspace(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isspace(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_istitle__doc__,
"B.istitle() -> bool\n"
"\n"
"Return True if B is a titlecased string and there is at least one\n"
"character in B, i.e. uppercase characters may only follow uncased\n"
"characters and lowercase characters only cased ones. Return False\n"
"otherwise.");

static PyObject *
bytearray_istitle(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_istitle(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_isupper__doc__,
"B.isupper() -> bool\n"
"\n"
"Return True if all cased characters in B are uppercase and there is\n"
"at least one cased character in B, False otherwise.");

static PyObject *
bytearray_isupper(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_isupper(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyObject *
bytearray_ljust(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_ljust(self, args, nargs);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_lower__doc__,
"B.lower() -> copy of B\n"
"\n"
"Return a copy of B with all ASCII characters converted to lowercase.");

static PyObject *
bytearray_lower(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_lower(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyObject *
bytearray_rjust(PyObject *self, PyObject *const *args, Py_ssize_t nargs)
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_rjust(self, args, nargs);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_swapcase__doc__,
"B.swapcase() -> copy of B\n"
"\n"
"Return a copy of B with uppercase ASCII characters converted\n"
"to lowercase ASCII and vice versa.");

static PyObject *
bytearray_swapcase(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_swapcase(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_title__doc__,
"B.title() -> copy of B\n"
"\n"
"Return a titlecased version of B, i.e. ASCII words start with\n"
"uppercase characters, all remaining cased characters have lowercase.");

static PyObject *
bytearray_title(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_title(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

PyDoc_STRVAR(bytearray_upper__doc__,
"B.upper() -> copy of B\n"
"\n"
"Return a copy of B with all ASCII characters converted to uppercase.");

static PyObject *
bytearray_upper(PyObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_upper(self, NULL);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyObject *
bytearray_zfill(PyObject *self, PyObject *arg)
{
    PyObject *ret;
    Py_BEGIN_CRITICAL_SECTION(self);
    ret = stringlib_zfill(self, arg);
    Py_END_CRITICAL_SECTION();
    return ret;
}

static PyMethodDef bytearray_methods[] = {
    {"__alloc__", bytearray_alloc, METH_NOARGS, bytearray___alloc____doc__},
    BYTEARRAY_REDUCE_METHODDEF
    BYTEARRAY_REDUCE_EX_METHODDEF
    BYTEARRAY_SIZEOF_METHODDEF
    BYTEARRAY_APPEND_METHODDEF
    {"capitalize", bytearray_capitalize, METH_NOARGS, bytearray_capitalize__doc__},
    {"center", _PyCFunction_CAST(bytearray_center), METH_FASTCALL, stringlib_center__doc__},
    BYTEARRAY_CLEAR_METHODDEF
    BYTEARRAY_COPY_METHODDEF
    BYTEARRAY_COUNT_METHODDEF
    BYTEARRAY_DECODE_METHODDEF
    BYTEARRAY_ENDSWITH_METHODDEF
    {"expandtabs", _PyCFunction_CAST(bytearray_expandtabs), METH_FASTCALL|METH_KEYWORDS, stringlib_expandtabs__doc__},
    BYTEARRAY_EXTEND_METHODDEF
    BYTEARRAY_FIND_METHODDEF
    BYTEARRAY_FROMHEX_METHODDEF
    BYTEARRAY_HEX_METHODDEF
    BYTEARRAY_INDEX_METHODDEF
    BYTEARRAY_INSERT_METHODDEF
    {"isalnum", bytearray_isalnum, METH_NOARGS, bytearray_isalnum__doc__},
    {"isalpha", bytearray_isalpha, METH_NOARGS, bytearray_isalpha__doc__},
    {"isascii", bytearray_isascii, METH_NOARGS, bytearray_isascii__doc__},
    {"isdigit", bytearray_isdigit, METH_NOARGS, bytearray_isdigit__doc__},
    {"islower", bytearray_islower, METH_NOARGS, bytearray_islower__doc__},
    {"isspace", bytearray_isspace, METH_NOARGS, bytearray_isspace__doc__},
    {"istitle", bytearray_istitle, METH_NOARGS, bytearray_istitle__doc__},
    {"isupper", bytearray_isupper, METH_NOARGS, bytearray_isupper__doc__},
    BYTEARRAY_JOIN_METHODDEF
    {"ljust", _PyCFunction_CAST(bytearray_ljust), METH_FASTCALL, stringlib_ljust__doc__},
    {"lower", bytearray_lower, METH_NOARGS, bytearray_lower__doc__},
    BYTEARRAY_LSTRIP_METHODDEF
    BYTEARRAY_MAKETRANS_METHODDEF
    BYTEARRAY_PARTITION_METHODDEF
    BYTEARRAY_POP_METHODDEF
    BYTEARRAY_REMOVE_METHODDEF
    BYTEARRAY_REPLACE_METHODDEF
    BYTEARRAY_REMOVEPREFIX_METHODDEF
    BYTEARRAY_REMOVESUFFIX_METHODDEF
    BYTEARRAY_RESIZE_METHODDEF
    BYTEARRAY_REVERSE_METHODDEF
    BYTEARRAY_RFIND_METHODDEF
    BYTEARRAY_RINDEX_METHODDEF
    {"rjust", _PyCFunction_CAST(bytearray_rjust), METH_FASTCALL, stringlib_rjust__doc__},
    BYTEARRAY_RPARTITION_METHODDEF
    BYTEARRAY_RSPLIT_METHODDEF
    BYTEARRAY_RSTRIP_METHODDEF
    BYTEARRAY_SPLIT_METHODDEF
    BYTEARRAY_SPLITLINES_METHODDEF
    BYTEARRAY_STARTSWITH_METHODDEF
    BYTEARRAY_STRIP_METHODDEF
    {"swapcase", bytearray_swapcase, METH_NOARGS, bytearray_swapcase__doc__},
    BYTEARRAY_TAKE_BYTES_METHODDEF
    {"title", bytearray_title, METH_NOARGS, bytearray_title__doc__},
    BYTEARRAY_TRANSLATE_METHODDEF
    {"upper", bytearray_upper, METH_NOARGS, bytearray_upper__doc__},
    {"zfill", bytearray_zfill, METH_O, stringlib_zfill__doc__},
    {NULL, NULL}  /* sentinel */
};

static PyNumberMethods bytearray_as_number = {
    .nb_remainder = bytearray_mod,
};

static PySequenceMethods bytearray_as_sequence = {
    .sq_length = bytearray_length,
    .sq_concat = PyByteArray_Concat,
    .sq_repeat = bytearray_repeat,
    .sq_item = bytearray_getitem,
    .sq_ass_item = bytearray_setitem,
    .sq_contains = bytearray_contains,
    .sq_inplace_concat = bytearray_iconcat,
    .sq_inplace_repeat = bytearray_irepeat,
};

static PyMappingMethods bytearray_as_mapping = {
    .mp_length = bytearray_length,
    .mp_subscript = bytearray_subscript,
    .mp_ass_subscript = bytearray_ass_subscript,
};

static PyBufferProcs bytearray_as_buffer = {
    .bf_getbuffer = bytearray_getbuffer,
    .bf_releasebuffer = bytearray_releasebuffer,
};

PyTypeObject PyByteArray_Type = {
    PyVarObject_HEAD_INIT(&PyType_Type, 0)
    .tp_name = "bytearray",
    .tp_basicsize = sizeof(PyByteArrayObject),
    .tp_dealloc = bytearray_dealloc,
    .tp_repr = bytearray_repr,
    .tp_as_number = &bytearray_as_number,
    .tp_as_sequence = &bytearray_as_sequence,
    .tp_as_mapping = &bytearray_as_mapping,
    .tp_str = bytearray_str,
    .tp_as_buffer = &bytearray_as_buffer,
    .tp_flags = Py_TPFLAGS_DEFAULT |
        Py_TPFLAGS_BASETYPE |
        _Py_TPFLAGS_MATCH_SELF,
    .tp_doc = bytearray__doc__,
    .tp_richcompare = bytearray_richcompare,
    .tp_iter = bytearray_iter,
    .tp_methods = bytearray_methods,
    .tp_init = bytearray___init__,
    .tp_alloc = PyType_GenericAlloc,
    .tp_new = bytearray_new,
    .tp_free = PyObject_Free,
    .tp_version_tag = _Py_TYPE_VERSION_BYTEARRAY,
};

/* bytearray_iterator */

PyDoc_STRVAR(bytearray_iterator___length_hint____doc__,
"Private method returning an estimate of len(list(it)).");

PyDoc_STRVAR(bytearray_iterator___setstate____doc__,
"Set state information for unpickling.");

static PyMethodDef bytearray_iterator_methods[] = {
    {"__length_hint__", bytearrayiter_length_hint, METH_NOARGS, bytearray_iterator___length_hint____doc__},
    {"__reduce__", bytearrayiter_reduce, METH_NOARGS, bytearray_reduce__doc__},
    {"__setstate__", bytearrayiter_setstate, METH_O, bytearray_iterator___setstate____doc__},
    {NULL, NULL}  /* sentinel */
};

PyTypeObject PyByteArrayIter_Type = {
    PyVarObject_HEAD_INIT(&PyType_Type, 0)
    .tp_name = "bytearray_iterator",
    .tp_basicsize = sizeof(bytesiterobject),
    .tp_dealloc = bytearrayiter_dealloc,
    .tp_flags = Py_TPFLAGS_DEFAULT |
        Py_TPFLAGS_HAVE_GC,
    .tp_traverse = bytearrayiter_traverse,
    .tp_iter = PyObject_SelfIter,
    .tp_iternext = bytearrayiter_next,
    .tp_methods = bytearray_iterator_methods,
};
