"""bytes() construction, written as Python.

Every function here becomes the C function of the same name, generated by
Tools/pyspec/emit_c.py into Objects/clinic/bytesobject_pyspec.c.h.
bytes_new implements the clinic function "bytes.__new__ as bytes_new": it
becomes bytes_new_impl(), and Argument Clinic's vectorcall for bytes calls
the bytes_new_nargsN() versions partially evaluated for exactly bytes.

Run Tools/pyspec/test_bytes_spec.py to compare the spec (executed as
Python) with the built interpreter's bytes().
"""

from pyspec_runtime import NULL, C, cstr, isinstance, fqname, tp_name


def bytes_new(cls: type[bytes], source: object = NULL, encoding: cstr = NULL,
              errors: cstr = NULL):
    """bytes.__new__"""
    if cls is not bytes:
        value = bytes_new(bytes, source, encoding, errors)
        return C.bytes_subtype_new(cls, value)
    if source is NULL:
        if encoding is not NULL:
            raise TypeError("encoding without a string argument")
        if errors is not NULL:
            raise TypeError("errors without a string argument")
        return b""
    if encoding is not NULL:
        if not isinstance(source, str):
            raise TypeError("encoding without a string argument")
        return C.PyUnicode_AsEncodedString(source, encoding, errors)
    if errors is not NULL:
        if isinstance(source, str):
            raise TypeError("string argument without an encoding")
        raise TypeError("errors without a string argument")
    # We'd like to call PyObject_Bytes here, but we need to check for an
    # integer argument before deferring to PyBytes_FromObject, something
    # PyObject_Bytes doesn't do.
    if (func := C.lookup_special(source, "__bytes__")) is not NULL:
        result = func()
        if not isinstance(result, bytes):
            raise TypeError(f"{fqname(type(source))}.__bytes__() must return "
                            f"a bytes, not {fqname(type(result))}")
        return result
    if isinstance(source, str):
        raise TypeError("string argument without an encoding")
    # Is it an integer?
    if hasattr(type(source), "__index__"):
        try:
            size = C.PyNumber_AsSsize_t(source, OverflowError)
        except TypeError:
            return PyBytes_FromObject(source)
        if size < 0:
            raise ValueError("negative count")
        return C._PyBytes_FromSize(size, True)
    return PyBytes_FromObject(source)


def PyBytes_FromObject(x: object):
    if x is NULL:
        raise C.PyErr_BadInternalCall()
    if type(x) is bytes:
        return x
    # Use the modern buffer interface
    if hasattr(type(x), "__buffer__"):
        return C._PyBytes_FromBuffer(x)
    if type(x) is list or type(x) is tuple:
        with C.critical_section_sequence_fast(x):
            result = C._PyBytes_FromSequence_lock_held(x)
        if result is not NULL:
            return result
    if not isinstance(x, str):
        try:
            it = iter(x)
        except TypeError:
            pass
        else:
            return C._PyBytes_FromIterator(it, x)
    raise TypeError(f"cannot convert '{tp_name(type(x))}' object to bytes")


# ---------------------------------------------------------------------------
# C API catalog
#
# One entry per C API function defined in Objects/bytesobject.c (public
# PyBytes_* / PyBytesWriter_* and internal _PyBytes_* / _Py_bytes_*):
# its C signature, reference ownership, error convention and whether it
# may run Python code, written with the facts vocabulary of
# Tools/pyspec/capi.py.  Body ``...`` means the C function is written by
# hand; PyBytes_FromObject above has a real body, so its facts are derived
# from it and not repeated here.  Parameter names and docstrings are the
# ones of Doc/c-api/bytes.rst (the future single source for the docs and
# Doc/data/refcounts.dat); stable ABI membership is read from
# Misc/stable_abi.toml, not repeated.  Lib/test/test_capi/
# test_pyspec_catalog.py compares all of this with the headers, the C
# definitions, the docs, refcounts.dat and the stable ABI data.
#
# The entries are nested in "if True:" only because the current
# Tools/pyspec/emit_c.py lowers every top-level function of the spec to C;
# once the emitter skips ``...`` stubs, dedent this block.

from capi import (InOut, New, NoError, NullIn, OnError, Out,  # noqa: E402
                  Py_ssize_t, RunsPython, Steals, char_p,
                  const_void_p, pointer, va_list, void_p)

PyBytesWriter_p = pointer('PyBytesWriter')

PyBytes_FromObject.__doc__ = r"""
    Return the bytes representation of object *o* that implements the buffer
    protocol.

    .. note::
       If the object implements the buffer protocol, then the buffer
       must not be mutated while the bytes object is being created.
    """

if True:
    def PyBytes_FromStringAndSize(v: cstr, len: Py_ssize_t) -> New[object]:
        r"""Return a new bytes object with a copy of the string *v* as value and length
        *len* on success, and ``NULL`` on failure.  If *v* is ``NULL``, the contents of
        the bytes object are uninitialized.

        .. soft-deprecated:: 3.15
           Use the :c:type:`PyBytesWriter` API instead of
           ``PyBytes_FromStringAndSize(NULL, len)``.
        """
        ...


    def PyBytes_FromString(v: cstr) -> New[object]:
        r"""Return a new bytes object with a copy of the string *v* as value on success,
        and ``NULL`` on failure.  The parameter *v* must not be ``NULL``; it will not be
        checked.
        """
        ...


    def PyBytes_FromFormatV(format: cstr, vargs: va_list) -> New[object]:
        r"""Identical to :c:func:`PyBytes_FromFormat` except that it takes exactly two
        arguments.
        """
        ...


    def PyBytes_FromFormat(format: cstr, *args: ...) -> New[object]:
        r"""Take a C :c:func:`printf`\ -style *format* string and a variable number of
        arguments, calculate the size of the resulting Python bytes object and return
        a bytes object with the values formatted into it.  The variable arguments
        must be C types and must correspond exactly to the format characters in the
        *format* string.  The following format characters are allowed:

        .. % XXX: This should be exactly the same as the table in PyErr_Format.
        .. % One should just refer to the other.

        .. tabularcolumns:: |l|l|L|

        +-------------------+---------------+--------------------------------+
        | Format Characters | Type          | Comment                        |
        +===================+===============+================================+
        | ``%%``            | *n/a*         | The literal % character.       |
        +-------------------+---------------+--------------------------------+
        | ``%c``            | int           | A single byte,                 |
        |                   |               | represented as a C int.        |
        +-------------------+---------------+--------------------------------+
        | ``%d``            | int           | Equivalent to                  |
        |                   |               | ``printf("%d")``. [1]_         |
        +-------------------+---------------+--------------------------------+
        | ``%u``            | unsigned int  | Equivalent to                  |
        |                   |               | ``printf("%u")``. [1]_         |
        +-------------------+---------------+--------------------------------+
        | ``%ld``           | long          | Equivalent to                  |
        |                   |               | ``printf("%ld")``. [1]_        |
        +-------------------+---------------+--------------------------------+
        | ``%lu``           | unsigned long | Equivalent to                  |
        |                   |               | ``printf("%lu")``. [1]_        |
        +-------------------+---------------+--------------------------------+
        | ``%zd``           | :c:type:`\    | Equivalent to                  |
        |                   | Py_ssize_t`   | ``printf("%zd")``. [1]_        |
        +-------------------+---------------+--------------------------------+
        | ``%zu``           | size_t        | Equivalent to                  |
        |                   |               | ``printf("%zu")``. [1]_        |
        +-------------------+---------------+--------------------------------+
        | ``%i``            | int           | Equivalent to                  |
        |                   |               | ``printf("%i")``. [1]_         |
        +-------------------+---------------+--------------------------------+
        | ``%x``            | int           | Equivalent to                  |
        |                   |               | ``printf("%x")``. [1]_         |
        +-------------------+---------------+--------------------------------+
        | ``%s``            | const char\*  | A null-terminated C character  |
        |                   |               | array.                         |
        +-------------------+---------------+--------------------------------+
        | ``%p``            | const void\*  | The hex representation of a C  |
        |                   |               | pointer. Mostly equivalent to  |
        |                   |               | ``printf("%p")`` except that   |
        |                   |               | it is guaranteed to start with |
        |                   |               | the literal ``0x`` regardless  |
        |                   |               | of what the platform's         |
        |                   |               | ``printf`` yields.             |
        +-------------------+---------------+--------------------------------+

        An unrecognized format character causes all the rest of the format string to be
        copied as-is to the result object, and any extra arguments discarded.

        .. [1] For integer specifiers (d, u, ld, lu, zd, zu, i, x): the 0-conversion
           flag has effect even when a precision is given.
        """
        ...


    def _PyBytes_FormatEx(
            format: cstr,
            format_len: Py_ssize_t,
            args: object,
            use_bytearray: int
    ) -> RunsPython[New[object]]:
        ...


    def _PyBytes_DecodeEscape2(
            s: cstr,
            len: Py_ssize_t,
            errors: cstr,
            first_invalid_escape_char: Out[int],
            first_invalid_escape_ptr: Out[cstr]
    ) -> New[object]:
        ...


    def PyBytes_DecodeEscape(
            s: cstr,
            len: Py_ssize_t,
            errors: cstr,
            unicode: Py_ssize_t,
            recode_encoding: cstr
    ) -> RunsPython[New[object]]:
        r"""Unescape a backslash-escaped string *s*. *s* must not be ``NULL``.
        *len* must be the size of *s*.

        *errors* must be one of ``"strict"``, ``"replace"``, or ``"ignore"``. If
        *errors* is ``NULL``, then ``"strict"`` is used by default.

        On success, this function returns a :term:`strong reference` to a Python
        :class:`bytes` object containing the unescaped string. On failure, this
        function returns ``NULL`` with an exception set.

        .. versionchanged:: 3.9
           *unicode* and *recode_encoding* are now unused.
        """
        ...


    def PyBytes_Size(o: object) -> OnError[Py_ssize_t, -1]:
        r"""Return the length of the bytes in bytes object *o*.
        """
        ...


    def PyBytes_AsString(o: object) -> OnError[char_p, NULL]:
        r"""Return a pointer to the contents of *o*.  The pointer
        refers to the internal buffer of *o*, which consists of ``len(o) + 1``
        bytes.  The last byte in the buffer is always null, regardless of
        whether there are any other null bytes.  The data must not be
        modified in any way, unless the object was just created using
        ``PyBytes_FromStringAndSize(NULL, size)``. It must not be deallocated.  If
        *o* is not a bytes object at all, :c:func:`PyBytes_AsString` returns ``NULL``
        and raises :exc:`TypeError`.
        """
        ...


    def PyBytes_AsStringAndSize(
            obj: object,
            buffer: Out[char_p],
            length: Out[Py_ssize_t]
    ) -> OnError[int, -1]:
        r"""Return the null-terminated contents of the object *obj*
        through the output variables *buffer* and *length*.
        Returns ``0`` on success.

        If *length* is ``NULL``, the bytes object
        may not contain embedded null bytes;
        if it does, the function returns ``-1`` and a :exc:`ValueError` is raised.

        The buffer refers to an internal buffer of *obj*, which includes an
        additional null byte at the end (not counted in *length*).  The data
        must not be modified in any way, unless the object was just created using
        ``PyBytes_FromStringAndSize(NULL, size)``.  It must not be deallocated.  If
        *obj* is not a bytes object at all, :c:func:`PyBytes_AsStringAndSize`
        returns ``-1`` and raises :exc:`TypeError`.

        .. versionchanged:: 3.5
           Previously, :exc:`TypeError` was raised when embedded null bytes were
           encountered in the bytes object.
        """
        ...


    def _PyBytes_Find(
            haystack: cstr,
            len_haystack: Py_ssize_t,
            needle: cstr,
            len_needle: Py_ssize_t,
            offset: Py_ssize_t
    ) -> NoError[Py_ssize_t]:
        ...


    def _PyBytes_ReverseFind(
            haystack: cstr,
            len_haystack: Py_ssize_t,
            needle: cstr,
            len_needle: Py_ssize_t,
            offset: Py_ssize_t
    ) -> NoError[Py_ssize_t]:
        ...


    def PyBytes_Repr(bytes: object, smartquotes: int) -> New[object]:
        r"""Get the string representation of *bytes*. This function is currently used to
        implement :meth:`!bytes.__repr__` in Python.

        This function does not do type checking; it is undefined behavior to pass
        *bytes* as a non-bytes object or ``NULL``.

        If *smartquotes* is true, the representation will use a double-quoted string
        instead of single-quoted string when single-quotes are present in *bytes*.
        For example, the byte string ``'Python'`` would be represented as
        ``b"'Python'"`` when *smartquotes* is true, or ``b'\'Python\''`` when it is
        false.

        On success, this function returns a :term:`strong reference` to a
        :class:`str` object containing the representation. On failure, this
        returns ``NULL`` with an exception set.
        """
        ...


    def _Py_bytes_repr(
            data: cstr,
            length: Py_ssize_t,
            smartquotes: int,
            classname: cstr
    ) -> New[object]:
        ...


    def _PyBytes_Concat(a: object, b: object) -> RunsPython[New[object]]:
        ...


    def _PyBytes_Repeat(self: object, n: Py_ssize_t) -> New[object]:
        ...


    def PyBytes_Join(sep: object, iterable: object) -> RunsPython[New[object]]:
        r"""Similar to ``sep.join(iterable)`` in Python.

        *sep* must be Python :class:`bytes` object.
        (Note that :c:func:`PyUnicode_Join` accepts ``NULL`` separator and treats
        it as a space, whereas :c:func:`PyBytes_Join` doesn't accept ``NULL``
        separator.)

        *iterable* must be an iterable object yielding objects that implement the
        :ref:`buffer protocol <bufferobjects>`.

        On success, return a new :class:`bytes` object.
        On error, set an exception and return ``NULL``.

        .. versionadded:: 3.14

        .. note::
           If *iterable* objects implement the buffer protocol, then the buffers
           must not be mutated while the new bytes object is being created.
        """
        ...


    def _PyBytes_FromHex(string: object, use_bytearray: int
                         ) -> RunsPython[New[object]]:
        ...


    def _PyBytes_CheckOverflow(
            self: object,
            addr: void_p,
            type_name: cstr
    ) -> None:
        ...


    def PyBytes_Concat(bytes: InOut[object], newpart: object
                       ) -> RunsPython[OnError[None, NullIn('bytes')]]:
        r"""Create a new bytes object in *\*bytes* containing the contents of *newpart*
        appended to *bytes*; the caller will own the new reference.
        The reference to the old value of *bytes* will be ":term:`stolen <steal>`".
        If the new object cannot be created, the old reference to *bytes* will still
        be "stolen", the value of *\*bytes* will be set to ``NULL``, and
        the appropriate exception will be set.

        .. note::
           If *newpart* implements the buffer protocol, then the buffer
           must not be mutated while the new bytes object is being created.
        """
        ...


    def PyBytes_ConcatAndDel(bytes: InOut[object], newpart: Steals[object]
                             ) -> RunsPython[OnError[None, NullIn('bytes')]]:
        r"""Create a new bytes object in *\*bytes* containing the contents of *newpart*
        appended to *bytes*.  This version releases the :term:`strong reference`
        to *newpart* (i.e. decrements its reference count).

        .. note::
           If *newpart* implements the buffer protocol, then the buffer
           must not be mutated while the new bytes object is being created.
        """
        ...


    def _PyBytes_IsMutable(self: object) -> NoError[int]:
        ...


    def _PyBytes_ResizeKeepOnError(
            pv: InOut[object],
            newsize: Py_ssize_t
    ) -> OnError[int, -1]:
        ...


    def _PyBytes_Resize(
            bytes: InOut[object],
            newsize: Py_ssize_t
    ) -> OnError[int, -1, NullIn('bytes')]:
        r"""Resize a bytes object. *newsize* will be the new length of the bytes object.
        You can think of it as creating a new bytes object and destroying the old
        one, only more efficiently.

        Pass the address of an
        existing bytes object as an lvalue (it may be written into), and the new size
        desired.  On success, *\*bytes* holds the resized bytes object and ``0`` is
        returned; the address in *\*bytes* may differ from its input value.  If the
        reallocation fails, the original bytes object at *\*bytes* is deallocated,
        *\*bytes* is set to ``NULL``, :exc:`MemoryError` is set, and ``-1`` is
        returned.

        While bytes objects are usually immutable in Python, this special C API
        allows mutating a bytes object in-place. The returned bytes object can still
        be mutated using :c:func:`PyBytes_AsString`; except if *newsize* is
        zero in which case it returns the immutable empty bytes string.

        .. soft-deprecated:: 3.15
           Use the :c:type:`PyBytesWriter` API instead.
        """
        ...


    def _PyBytes_RepeatBuffer(
            dest: char_p,
            len_dest: Py_ssize_t,
            src: cstr,
            len_src: Py_ssize_t
    ) -> None:
        ...


    def PyBytesWriter_Create(size: Py_ssize_t
                             ) -> OnError[PyBytesWriter_p, NULL]:
        r"""Create a :c:type:`PyBytesWriter` to write *size* bytes.

        If *size* is greater than zero, allocate *size* bytes, and set the
        writer size to *size*. The caller is responsible to write *size*
        bytes using :c:func:`PyBytesWriter_GetData`.
        This function does not overallocate.

        On error, set an exception and return ``NULL``.

        *size* must be positive or zero.
        """
        ...


    def _PyBytesWriter_CreateByteArray(
            size: Py_ssize_t
    ) -> OnError[PyBytesWriter_p, NULL]:
        ...


    def PyBytesWriter_Discard(writer: Steals[PyBytesWriter_p]) -> None:
        r"""Discard a :c:type:`PyBytesWriter` created by :c:func:`PyBytesWriter_Create`.

        Do nothing if *writer* is ``NULL``.

        The writer instance is invalid after the call.
        No API can be called on the writer after :c:func:`PyBytesWriter_Discard`.
        """
        ...


    def PyBytesWriter_FinishWithSize(
            writer: Steals[PyBytesWriter_p],
            size: Py_ssize_t
    ) -> New[object]:
        r"""Similar to :c:func:`PyBytesWriter_Finish`, but resize the writer
        to *size* bytes before creating the :class:`bytes` object.
        """
        ...


    def PyBytesWriter_Finish(writer: Steals[PyBytesWriter_p]) -> New[object]:
        r"""Finish a :c:type:`PyBytesWriter` created by
        :c:func:`PyBytesWriter_Create`.

        On success, return a Python :class:`bytes` object.
        On error, set an exception and return ``NULL``.

        The writer instance is invalid after the call in any case.
        No API can be called on the writer after :c:func:`PyBytesWriter_Finish`.
        """
        ...


    def PyBytesWriter_FinishWithPointer(
            writer: Steals[PyBytesWriter_p],
            buf: void_p
    ) -> New[object]:
        r"""Similar to :c:func:`PyBytesWriter_Finish`, but resize the writer
        using *buf* pointer before creating the :class:`bytes` object.

        Set an exception and return ``NULL`` if *buf* pointer is outside the
        internal buffer bounds.

        Function pseudo-code::

            Py_ssize_t size = (char*)buf - (char*)PyBytesWriter_GetData(writer);
            return PyBytesWriter_FinishWithSize(writer, size);
        """
        ...


    def PyBytesWriter_GetData(writer: PyBytesWriter_p) -> NoError[void_p]:
        r"""Get the writer data: start of the internal buffer.

        The pointer remains valid until a :c:type:`PyBytesWriter` function other
        than :c:func:`PyBytesWriter_GetData` or :c:func:`PyBytesWriter_GetSize` is
        called on *writer*.

        The function cannot fail.
        """
        ...


    def PyBytesWriter_GetSize(writer: PyBytesWriter_p) -> NoError[Py_ssize_t]:
        r"""Get the writer size.

        The function does not invalidate pointers returned by
        :c:func:`PyBytesWriter_GetData`.

        The function cannot fail.
        """
        ...


    def PyBytesWriter_Resize(
            writer: PyBytesWriter_p,
            size: Py_ssize_t
    ) -> OnError[int, -1]:
        r"""Resize the writer to *size* bytes. It can be used to enlarge or to
        shrink the writer.
        This function typically overallocates to achieve amortized performance when
        resizing multiple times.

        Newly allocated bytes are left uninitialized.

        On success, return ``0``.
        On error, set an exception and return ``-1``.

        *size* must be positive or zero.
        """
        ...


    def PyBytesWriter_Grow(
            writer: PyBytesWriter_p,
            grow: Py_ssize_t
    ) -> OnError[int, -1]:
        r"""Resize the writer by adding *grow* bytes to the current writer size.
        This function typically overallocates to achieve amortized performance when
        resizing multiple times.

        Newly allocated bytes are left uninitialized.

        On success, return ``0``.
        On error, set an exception and return ``-1``.

        *grow* can be negative to shrink the writer.
        """
        ...


    def PyBytesWriter_GrowAndUpdatePointer(
            writer: PyBytesWriter_p,
            size: Py_ssize_t,
            buf: void_p
    ) -> OnError[void_p, NULL]:
        r"""Similar to :c:func:`PyBytesWriter_Grow`, but update also the *buf*
        pointer.

        The *buf* pointer is moved if the internal buffer is moved in memory.
        The *buf* relative position within the internal buffer is left
        unchanged.

        On error, set an exception and return ``NULL``.

        *buf* must not be ``NULL``.

        Function pseudo-code::

            Py_ssize_t pos = (char*)buf - (char*)PyBytesWriter_GetData(writer);
            if (PyBytesWriter_Grow(writer, size) < 0) {
                return NULL;
            }
            return (char*)PyBytesWriter_GetData(writer) + pos;
        """
        ...


    def PyBytesWriter_WriteBytes(
            writer: PyBytesWriter_p,
            bytes: const_void_p,
            size: Py_ssize_t
    ) -> OnError[int, -1]:
        r"""Grow the *writer* internal buffer by *size* bytes,
        write *size* bytes of *bytes* at the *writer* end,
        and add *size* to the *writer* size.

        If *size* is equal to ``-1``, call ``strlen(bytes)`` to get the
        string length.

        On success, return ``0``.
        On error, set an exception and return ``-1``.
        """
        ...


    def PyBytesWriter_Format(
            writer: PyBytesWriter_p,
            format: cstr,
            *args: ...
    ) -> OnError[int, -1]:
        r"""Similar to :c:func:`PyBytes_FromFormat`, but write the output directly at
        the writer end. Grow the writer internal buffer on demand. Then add the
        written size to the writer size.

        On success, return ``0``.
        On error, set an exception and return ``-1``.
        """
        ...
